builds:
  - main: main.go
    binary: csvToCamt
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Linux
    windows: Windows
  files:
    - config.yaml
    - LICENSE
